# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0003_auto_20170727_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Um',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='prezzi',
            name='um',
        ),
    ]
