# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0006_auto_20170827_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulari',
            name='data',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AlterField(
            model_name='prezzi',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
