# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulari', '0008_auto_20170827_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='prezzi',
            name='autore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
