# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulari', '0009_prezzi_autore'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulari',
            name='autore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulari',
            name='mat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formulari.Materiali'),
        ),
        migrations.AddField(
            model_name='formulari',
            name='qu',
            field=models.FloatField(default=1),
        ),
    ]
