# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0010_auto_20170831_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulari',
            name='stato',
            field=models.CharField(choices=[('AP', 'Aperto'), ('RP', 'Riepilogato'), ('CH', 'Chiuso')], default='AP', max_length=2),
        ),
    ]
