# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0011_formulari_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulari',
            name='stato',
            field=models.CharField(choices=[('AP', 'Aperto'), ('RP', 'Riepilogato'), ('CH', 'Chiuso'), ('ER', 'Errore')], default='AP', max_length=2),
        ),
    ]
