# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0013_auto_20170911_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulari',
            name='prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formulari.Produttori'),
        ),
        migrations.AlterField(
            model_name='formulari',
            name='qu',
            field=models.FloatField(),
        ),
    ]
