# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0014_auto_20170912_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulari',
            name='imp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
