# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0015_formulari_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulari',
            name='stato',
            field=models.CharField(choices=[('AP', 'Aperto'), ('RP', 'Riepilogato'), ('CH', 'Chiuso'), ('ER', 'Errore'), ('IA', 'Inattivo')], default='AP', max_length=2),
        ),
    ]
