# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-26 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0017_auto_20171026_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ripartizioni',
            name='mail',
            field=models.EmailField(max_length=200),
        ),
    ]
