# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulari', '0019_auto_20171114_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riepiloghi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('stato', models.CharField(choices=[('PR', 'Pronto'), ('IN', 'Inviato'), ('PA', 'Pagato'), ('ER', 'Errore')], default='PR', max_length=2)),
                ('autore', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulari.Anagrafica')),
            ],
        ),
        migrations.AddField(
            model_name='formulari',
            name='riepi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulari.Riepiloghi'),
        ),
    ]
