# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0020_auto_20171129_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulari',
            name='riepi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulari.Riepiloghi'),
        ),
    ]
