# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0021_auto_20171129_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='riepiloghi',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='upld/'),
        ),
    ]
