# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0022_riepiloghi_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='riepiloghi',
            name='ric',
            field=models.FileField(blank=True, null=True, upload_to='upld/ricevute/'),
        ),
        migrations.AlterField(
            model_name='riepiloghi',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='upld/riepiloghi/'),
        ),
    ]
