# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-05 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulari', '0024_anagrafica_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulari',
            name='riepi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulari.Riepiloghi'),
        ),
    ]
